// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ReferenceSwitcher
{
    static class Vsix
    {
        public const string Id = "7255b31e-0997-4b88-9498-93fb5606e249";
        public const string Name = "Reference Switcher";
        public const string Description = @"Switch from PackageReferences to ProjectReferences to make it easier to test/debug/develop libraries.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Andreas Stolpmann";
        public const string Tags = "";
    }
}
