// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ReferenceSwitcher
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidReferenceSwitcherPackageString = "7f345bd6-4dc8-45a7-ab23-ef7c1b11e86e";
        public const string guidReferenceSwitcherPackageCmdSetString = "ecb71e43-6797-48d5-91a9-44d6c6d7ef87";
        public const string guidImagesString = "c10dd596-1d7d-4f73-9d25-47be2fba389d";
        public static Guid guidReferenceSwitcherPackage = new Guid(guidReferenceSwitcherPackageString);
        public static Guid guidReferenceSwitcherPackageCmdSet = new Guid(guidReferenceSwitcherPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
